### ISSUE TITLE
[AVM Module Issue]: Terraform Cloud not able to Run due to bad call

### ISSUE THREAD

**Issue by ebrookman** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#114]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

I am getting this error when trying to do a plan in Terraform Cloud. It appears as though a typo has been made as it is looking for azurern not azurerm 

 Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/azurern: provider registry registry.terraform.io does not have a
│ provider named registry.terraform.io/hashicorp/azurern
│ 
│ All modules should specify their required_providers so that external
│ consumers will get the correct providers when using a module. To see which
│ modules are currently depending on hashicorp/azurern, run the following
│ command:
│     terraform providers

**Comment by jchancellor-ms** [comment]
@ebrookman - Thanks for reaching out.  I did a search on the latest published version and found no instances where we have azurern in the current module.  Would you be able to confirm which version of the module you are using and also validate your provider configs in the calling module?

**Comment by ebrookman** [comment]
It started working without issue this morning.
