### ISSUE TITLE
[AVM Module Issue]: missing property: `vm_agent_platform_updates_enabled`

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#118]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.16.0

### Description

This property, introduced in azurerm v3.9.4, is missing from the windows & linux VM parameters:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine.html#vm_agent_platform_updates_enabled

**Comment by eclipse313** [comment]
I have the same problem. With every `apply` the value is overwritten again:

```
  # module.business_applications[0].module.server.module.host.azurerm_windows_virtual_machine.this[0] will be updated in-place
  ~ resource "azurerm_windows_virtual_machine" "this" {
        id                                                     = "/subscriptions/a2fdd2e9-54ce-46d5-b97d-a308578d4d23/resourceGroups/rg-bcd-avd-prod-dewc-business_applications/providers/Microsoft.Compute/virtualMachines/vm-bcd-app-main"
        name                                                   = "vm-bcd-app-main"
        tags                                                   = {}
      ~ vm_agent_platform_updates_enabled                      = true -> false
        # (41 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }
```

**Comment by jchancellor-ms** [comment]
@kewalaka - I'm pending AzureRM support this week and will look to add this capability as well.  Thanks for reporting this.

**Comment by jchancellor-ms** [comment]
Added this into the latest release, but it appears from the ARM swagger that the API value behind this is read-only.  Setting this to true will cause idempotency issues with deployments as the value will not change and the configuration will attempt to reset on each apply.  (see issue https://github.com/hashicorp/terraform-provider-azurerm/issues/27484) I'm leaving the value in for when the API moves this value from being read-only.

**Comment by eclipse313** [comment]
Thank you for the update. Would it be an option to use `ignore_changes` on `vm_agent_platform_updates_enabled` to eliminate the diff? It seems to me that the read-only-state wouldn't change in near future.

**Comment by IliassAK** [comment]
I've checked. It appears the ignore_changes for vm_agent_platform_updates_enabled is in version 0.19.3
