### ISSUE TITLE
[AVM Module Issue]: azurerm 4 compatibility

### ISSUE THREAD

**Issue by But4ler** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#121]
[AVM Module Issue]: azurerm 4 compatibility

Check for previous/existing GitHub issues

[X] I have checked for previous/existing GitHub issues
Issue Type?
Bug

(Optional) Module Version
v.0.16

(Optional) Correlation Id
No response

Description
Hi,

This modules current version constraints on the azurem provider prevents me from upgrading my terraform project.
Please issue an updated release with support for azurerm 4.x.

Other similaire problème
https://github.com/Azure/Azure-Verified-Modules/issues/1576
https://github.com/Azure/terraform-azurerm-avm-res-network-virtualnetwork/issues/146

if possible...
```hcl
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.71, < 5.0.0"
    }
```

Thanks :-)

**Comment by jchancellor-ms** [comment]
@But4ler - thanks for reporting this. I've been out of pocket for a few weeks, but will try to finish testing and 4.0 compatibility released this week. My apologies on the delay.
