### ISSUE TITLE
[AVM Module Issue]: hibernation_enabled in additional_capabilities missing

### ISSUE THREAD

**Issue by eclipse313** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#127]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Description

Since the azurerm provider (since version [v3.103.0](https://github.com/hashicorp/terraform-provider-azurerm/milestone/287)) hibernation_enabled [supports](
https://github.com/hashicorp/terraform-provider-azurerm/pull/25807), I think this should also be integrated here, as we should stay as close as possible to the functions of the original azurerm provider.

**Comment by eclipse313** [comment]
If you want, I can create a pull request for this, but I think the change is trivial.

**Comment by jchancellor-ms** [comment]
Adding this to release 0.17
