### ISSUE TITLE
Managed disk cannot be created in a different resource group from the virtual machine

### ISSUE THREAD

**Issue by LaurentLesle** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#20]
Managed disk support a resource_group_name attribute. The module is using an opiniated approach to set the resource group name as the one from the virtual machine.

This is an issue when customers want to store the managed disks in a different resource group as the vm.

<img width="796" alt="image" src="https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine/assets/4702224/2de6b6ae-8982-4f5f-8024-1c8a6ab9bdf0">

Proposed solution

```hcl
resource "azurerm_managed_disk" "this" {
  for_each = var.data_disk_managed_disks

  name                              = each.value.name
  location                          = local.location
  resource_group_name               = try(each.value.resource_group_name, data.azurerm_resource_group.virtualmachine_deployment.name)
  storage_account_type              = each.value.storage_account_type
...
}
```

**Comment by jchancellor-ms** [comment]
@LaurentLesle  - merged your PR for this fix.  Closing this issue with the fix and will re-open if additional issues are discovered.
