### ISSUE TITLE
Feature Request: System Assignmed Managed Identity Output

### ISSUE THREAD

**Issue by jaredfholgate** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#22]
There doesn't appear to be an output to get the details of the system assigned managed identity directly. This could simply accessing it.

**Comment by jchancellor-ms** [comment]
@jaredfholgate - Thanks for this.  I'll add an output for these values in the next few days

**Comment by jchancellor-ms** [comment]
@jaredfholgate - I confirmed that the system assigned managed identity values are already included in an output.  You can access the principal and tenant id values using the virtual_machine_azurerm output which includes all of the values exported by azurerm.

An example would look like:
`
output "managed_identity" {
  value = module.testvm.virtual_machine_azurerm.identity
}
`

or to access the principal_id
`output "system_managed_identity_id" {
   value = module.testvm.virtual_machine_azurerm.identity[0].principal_id
}
`

I'm going to close this issue for now, but please let me know if there is additional details you would like included in this output.

**Comment by jchancellor-ms** [comment]
Functionality exists, closing.

**Comment by jaredfholgate** [comment]
> @jaredfholgate Jared Holgate FTE - I confirmed that the system assigned managed identity values are already included in an output. You can access the principal and tenant id values using the virtual_machine_azurerm output which includes all of the values exported by azurerm.
> 
> An example would look like: `output "managed_identity" { value = module.testvm.virtual_machine_azurerm.identity }`
> 
> or to access the principal_id `output "system_managed_identity_id" { value = module.testvm.virtual_machine_azurerm.identity[0].principal_id } `
> 
> I'm going to close this issue for now, but please let me know if there is additional details you would like included in this output.

I know it already exists, it's just not very user friendly and is a very commonly required output. My request was to make it simpler to access and / or better documented. No problem if not a priority.

**Comment by jchancellor-ms** [comment]
@jaredfholgate - That's my fault, as I misunderstood the ask.  I also missed that there is a spec requirement to isolate the system managed identity as a separate output in RMFR7.  Re-opening this issue and will add to the code I'm including in the next release.

**Comment by jchancellor-ms** [comment]
@jaredfholgate - I've published v0.5.0 which includes a separate output with the principal id in alignment with the spec.  Please feel free to test and let me know if you encounter any additional issues.

**Comment by jchancellor-ms** [comment]
Closing this issue as fixed in version v0.5.0.
