### ISSUE TITLE
Depends_on missing on the extensions 

### ISSUE THREAD

**Issue by LaurentLesle** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#26]
When calling a custom script extension that format the data disks, Terraform trigger the custom script before all disks are attached to the virtual machine.

By adding a depends_on the disk attachments it fixes that issue.

**Comment by GargiAgrawalscb** [comment]
I am from Singapore SCB and working with Microsoft extensively on this terraform module for Vm disks creation and attachment. We are currently  blocked because of this change not present in the module. 
Please get this PR approval prioritized and unblock us.

**Comment by jchancellor-ms** [comment]
@LaurentLesle @GargiAgrawalscb - Depends on PR has been applied and released as v0.6.0.  Thanks for the submission.  Please let me know if there are any continuing issues.  I will close this issue on the PR, and reopen if any additional issues exist.

**Comment by GargiAgrawalscb** [comment]
Thanks @jchancellor-ms
