### ISSUE TITLE
Error: Deploying with winrm

### ISSUE THREAD

**Issue by ptsouk** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#29]
Providing a value for the winrm_listeners like the below:

`  winrm_listeners = [
    {
      protocol        = "Http"
    }
  ]
`
gives an error:

> │ Error: Invalid function argument
> │ 
> │   on .terraform/modules/vm01/main.windows_vm.tf line 151, in resource "azurerm_windows_virtual_machine" "this":
> │  151:     for_each = { for listener in var.winrm_listeners : sha256(listener) => listener }
> │ 
> │ Invalid value for "str" parameter: string required.

The line in main.windows_vm.tf is:
https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine/blob/27d9ec63b9344740e51bdd67dc0e3cf9bb15685c/main.windows_vm.tf#L151

Changing the line to :
`for_each = { for listener in var.winrm_listeners : sha256(jsonencode(listener)) => listener }` resolves it and the vm is deployed with winrm configured. Can you please check/advise? Thank you.

**Comment by jchancellor-ms** [comment]
@ptsouk - Thank you for this, I will run the review and make the changes this afternoon and test.  Should be able to get an updated version out later today if everything goes ok.

**Comment by jchancellor-ms** [comment]
@ptsouk - this has been corrected in release 0.7.0.  Can you please confirm that this resolves your issue?
