### ISSUE TITLE
Create a vm with an admin_password fails

### ISSUE THREAD

**Issue by LaurentLesle** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#42]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Bug

### (Optional) Module Version

0.8.0

### Description

Create a virtual machine with admin_password fails as Terraform cannot identity an element in the data.azurerm_key_vault_secret:

```bash
Error: Invalid index
│ 
│   on .terraform/modules/vm.instance.virtual_machine/locals.tf line 9, in locals:
│    9:     var.generate_admin_password_or_ssh_key ? random_password.admin_password[0].result : coalesce(var.admin_password, data.azurerm_key_vault_secret.admin_password[0].value) #use generated password, password variable, or vault reference (in order)
│     ├────────────────
│     │ data.azurerm_key_vault_secret.admin_password is empty tuple
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.
```

This issue is due to the module not using secret in keyvault.

tfvars used:
```hcl
# Do not generate admin password or SSH key per VM.
generate_admin_password_or_ssh_key   = false
admin_password                       = "Ver$£@$rFEfew£r3^34R43rf$£453" # just a random password

zone                    = "1"
virtualmachine_sku_size = "Standard_DC4s_v3"
virtualmachine_os_type  = "Windows"
patch_mode              = "AutomaticByPlatform"

source_image_reference = {
  publisher = "MicrosoftWindowsServer"
  offer     = "WindowsServer"
  sku       = "2022-datacenter-azure-edition-hotpatch"
  version   = "latest"
}

```

**Comment by LaurentLesle** [comment]
@jchancellor-ms will provide a PR for that issue

**Comment by jchancellor-ms** [comment]
Thanks @LaurentLesle .  This appears to be an issue with how coalesce handles the data resource.  I'll push a fix this afternoon. Will also add this to the backlog of examples options to include so this scenario gets tested regularly in the future.
