### ISSUE TITLE
Extensions are failing when using feature flags causing some values to be null

### ISSUE THREAD

**Issue by LaurentLesle** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#45]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Bug

### (Optional) Module Version

0.8.0

### Description

I am using a feature flag for an extension depending if it is Windows or Linux OS. 

For example if my deployment is a Windows OS, the linux extension is set to null and vice versa.

```hcl
  extensions = {
    manage_disks_linux = lower(var.virtualmachine_os_type) == "linux" && var.disk_management_script_template_path != null ? {
      name                        = "disk_management"
      failure_suppression_enabled = true
      publisher                   = "Microsoft.Azure.Extensions"
      type                        = "CustomScript"
      type_handler_version        = "2.1"

      protected_settings = jsonencode(
        {
          script = base64gzip(local.manifest_yaml_from_file)
        }
      )
    } : null
    manage_disks_windows = lower(var.virtualmachine_os_type) == "windows" && var.disk_management_script_template_path != null ? {
      name                        = "disk_management"
      failure_suppression_enabled = true
      publisher                   = "Microsoft.Compute"
      type                        = "CustomScriptExtension"
      type_handler_version        = "1.10"

      protected_settings = jsonencode(
        {
          commandToExecute = base64gzip(local.manifest_yaml_from_file)
        }
      )

    } : null
  }
```

It is causing the variable extension validation rule to fail as type is null

```hcl
validation {
    condition = length(var.extensions) == length(distinct([
      for e in var.extensions : e.type
    ]))
    error_message = "`type` in `vm_extensions` must be unique."
  }
```

possible workaround
```hcl
  validation {
    condition = can({
      for k in var.extensions : var.extensions[k].type => var.extensions[k] 
      if try(var.extensions[k].type, null) != null
    })
    error_message = "`type` in `vm_extensions` must be unique."
  }
```

It would also require the main.extensions.tf to be updated
```hcl
resource "azurerm_virtual_machine_extension" "this_extension" {
  for_each = toset([for k, v in nonsensitive(var.extensions) : k])
```
to
```hcl
for_each = toset([for k, v in nonsensitive(var.extensions) : k if try(v, null) != null])
```

**Comment by jchancellor-ms** [comment]
@LaurentLesle - I can't make your suggested changes as we would need to reference the value in the for_each which generates the dreaded known before apply issue.  Can you tell me if you calling module will work if you do something like this instead:

`    extensions =  (lower(var.virtualmachine_os_type) == "linux" && var.disk_management_script_template_path != null) ?  {
            manage_disks =  {
                name                        = "disk_management"
                failure_suppression_enabled = true
                publisher                   = "Microsoft.Azure.Extensions"
                type                        = "CustomScript"
                type_handler_version        = "2.1"

                protected_settings = jsonencode(
                    {
                    script = base64gzip(local.manifest_yaml_from_file)
                    }
                )
            }
        } : (lower(var.virtualmachine_os_type) == "windows" && var.disk_management_script_template_path != null) ? {
        manage_disks = {             
            name                        = "disk_management"
            failure_suppression_enabled = true
            publisher                   = "Microsoft.Compute"
            type                        = "CustomScriptExtension"
            type_handler_version        = "1.10"

            protected_settings = jsonencode(
                {
                commandToExecute = base64gzip(local.manifest_yaml_from_file)
                }
            )
        }
    } : {}`

**Comment by LaurentLesle** [comment]
Let me have a look

**Comment by jchancellor-ms** [comment]
Pending testing with @LaurentLesle.

**Comment by LaurentLesle** [comment]
on it

**Comment by LaurentLesle** [comment]
Found a different approach to address it. Closing it.
