### ISSUE TITLE
winrms is failing when certificates created during the same deployment of the virtual machine

### ISSUE THREAD

**Issue by LaurentLesle** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#46]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Bug

### (Optional) Module Version

0.8.0

### Description

Related to #29 #30 

The scenario is the following:

1. winrm_listener is set to https
2. winrm certificate is created during the same operation as the vm

Issue: dynamic winrm block is not created as the jsonencode(listener) is silently failing as the object will be known after the apply. This is related to the certificate secret_id not known at plan time.

winrm_listerners set to the module:
```hcl
winrm_listeners = [
    for v in var.winrm_listeners : {
      protocol = v.protocol
      certificate_url = coalesce(
        try(v.certificate_url, null),
        azurerm_key_vault_certificate.self_signed_winrm[sha256(jsonencode(v))].secret_id
      )
    } if lower(v.protocol) == "https"
  ]
```

Debug output shows the content of that variable. Showing the certificate_url will be known after apply
```bash
winrm_listeners = {
      + Appservers2    = {
          + winrm_listeners = {
              + "0" = [
                  + {
                      + certificate_url = (known after apply)
                      + protocol        = "Https"
                    },
                ]
              + "1" = [
                  + {
                      + certificate_url = (known after apply)
                      + protocol        = "Https"
                    },
                ]
            }
        }
```

Current code:
```hcl
  dynamic "winrm_listener" {
    for_each = { for listener in var.winrm_listeners : sha256(jsonencode(listener)) => listener }

    content {
      protocol        = winrm_listener.value.protocol
      certificate_url = winrm_listener.value.certificate_url
    }
  }
```

output of the terraform plan:
![image](https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine/assets/4702224/85e16f0b-c602-42e2-bb37-eee9518fcdbe)

*** Proposed Fix ***
main.windows_vm.tf
```hcl
dynamic "winrm_listener" {
    for_each = var.winrm_listeners

    content {
      protocol        = winrm_listener.value.protocol
      certificate_url = winrm_listener.value.certificate_url
    }
  }
```

Output of the plan (with proposed fix):
![image](https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine/assets/4702224/1a87b38a-9245-4b22-ae22-f93bc8064e69)

***winrm set to http and https***
Also working when set to http and https
![image](https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine/assets/4702224/a1edfa5b-1490-407a-9f62-002821694f12)

**Comment by jchancellor-ms** [comment]
@LaurentLesle - Good catch.  I did this initially to handle the potential for multiple listeners which was a poor design choice.  I'd like to test the proposed fix with multiple https listeners with different certs to make sure that we can support that configuration (even though the documentation doesn't make it clear whether that is a valid configuration).  I'll also add the creation of self-signed certs to the example with winRM so we get test coverage for both types.

**Comment by LaurentLesle** [comment]
Not closing that specific issue. Alternate solution provided when the internal fqdn is not required in the winrm certificate SAN - https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine/pull/47#issue-2217607516

**Comment by jchancellor-ms** [comment]
@LaurentLesle - I'm closing this based on your changes incorporated in version 0.10.0 .  Please let me know if there is anything outstanding on this specific issue and I will re-open.
