### ISSUE TITLE
[AVM Module Issue]: Feat: support for auto shutdown schedules

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#50]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Feature Request

### (Optional) Module Version

0.9.0

### Description

This is a request to add support for the autoshutdown schedule resource, i.e.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dev_test_global_vm_shutdown_schedule

The list of currently supported timezone names for Azure are here;

https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/timezones-overview?view=azuresql#list-of-supported-time-zones

I acknowledge this would be a 'bending' of the rules around the scope of a resource as per the definition of AVM modules (since shutdown schedule is not in the same RP as the VM).  Would be a nice addition though, and seems to sit logically with the VM module.

**Comment by jchancellor-ms** [comment]
@kewalaka - Thanks for the submission.  Let me review this with the core team to get a ruling on whether this would be within the intent of the module. We meet tomorrow, so I'll post an update after than conversation.

**Comment by jchancellor-ms** [comment]
@kewalaka - I added this feature to the module and included an example in the additional disks example.  Please feel free to test and re-open the issue if there is anything missing or in error.
