### ISSUE TITLE
[AVM Module Issue]: Add resource_group_name as optional for network_interfaces

### ISSUE THREAD

**Issue by bmcsorley-bh** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#65]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Allow the ability to specify a resource group name if the network interface and ip configuration should be created in a separate resource group from the virtual machine.

This functionality exists for data_disk_managed_disks.

**Comment by jchancellor-ms** [comment]
@bmcsorley-bh - This feature was implemented in release v0.13.0.  Please re-open this if you determine anything is missing or additional functionality is required.
