### ISSUE TITLE
[AVM Module Issue]: AVM Compute module raises security warnings with Checkov

### ISSUE THREAD

**Issue by giovannifl** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#72]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Security Bug

### Description

While executing Checkov checks on Terraform files where the AVM Compute module is used, following warnings are showed:

**Check: CKV_AZURE_114: "Ensure that key vault secrets have "content_type" set"**
FAILED for resource: module.avm-res-compute-dcvm-identity["vm01"].azurerm_key_vault_secret.admin_ssh_key[0]
File: /.external_modules/github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine/862ab3a36ace3192f4fe55e3ad99f3914eaf71ee/main.authentication.tf:50-57

            50 | resource "azurerm_key_vault_secret" "admin_ssh_key" {
            51 |   count = ((var.generate_admin_password_or_ssh_key == true) && (lower(var.virtualmachine_os_type) == "linux")) ? 1 : 0
            52 | 
            53 |   key_vault_id = var.admin_credential_key_vault_resource_id
            54 |   name         = coalesce(var.admin_generated_ssh_key_vault_secret_name, "${var.name}-${var.admin_username}-ssh-private-key")
            55 |   value        = tls_private_key.this[0].private_key_pem
            56 |   tags         = var.tags
            57 | }

Calling File: /core.tf:111-186
Guide: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/ensure-that-key-vault-secrets-have-content-type-set

**Check: CKV_AZURE_41: "Ensure that the expiration date is set on all secrets"**
FAILED for resource: module.avm-res-compute-dcvm-identity["vm01"].azurerm_key_vault_secret.admin_ssh_key[0]
File: /.external_modules/github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine/862ab3a36ace3192f4fe55e3ad99f3914eaf71ee/main.authentication.tf:50-57

            50 | resource "azurerm_key_vault_secret" "admin_ssh_key" {
            51 |   count = ((var.generate_admin_password_or_ssh_key == true) && (lower(var.virtualmachine_os_type) == "linux")) ? 1 : 0
            52 | 
            53 |   key_vault_id = var.admin_credential_key_vault_resource_id
            54 |   name         = coalesce(var.admin_generated_ssh_key_vault_secret_name, "${var.name}-${var.admin_username}-ssh-private-key")
            55 |   value        = tls_private_key.this[0].private_key_pem
            56 |   tags         = var.tags
            57 | }

Calling File: /core.tf:111-186
Guide: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/azure-policies/azure-secrets-policies/set-an-expiration-date-on-all-secrets

**Check: CKV_AZURE_50: "Ensure Virtual Machine Extensions are not Installed"**
FAILED for resource: module.avm-res-compute-dcvm-identity["vm01"].azurerm_linux_virtual_machine.this
File: /.external_modules/github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine/862ab3a36ace3192f4fe55e3ad99f3914eaf71ee/main.linux_vm.tf:1-154
Calling File: /core.tf:111-186
Guide: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/bc-azr-general-14

**Comment by jchancellor-ms** [comment]
@giovannifl - Thanks for reporting these items.  You should be able to work around each of these items with the currently released version of the module.  

For item 1, we include an SSH key or randomly generated password if you opt to not supply a login method.  These items are stored in a key vault but we don't tag them as each customer may have different tagging schemes.  You can however, opt to provide your own secret material by setting the `generate_admin_password_or_ssh_key` input to false, and then tag your secret in your key vault as needed to avoid the first error.  T

For item 2.  Extensions by themselves aren't necessarily security risks and most customers use one or more of them in some form.  (As an example, the Azure Monitoring Agent can be deployed as an extension and is recommended in most environments.)  However, we do expose the `allow_extension_operations` input mentioned in the finding, and it can be set from its default `true` value to `false`.  This will prevent that instance of the implementation from generating a finding.  

I'll leave this issue open for a few days, and feel free to post additional questions or responses here or close the issue if this response addresses your concerns.

**Comment by giovannifl** [comment]
@jchancellor-ms Thanks for your clarification.
The problem is that Checkov is raising these warning because "potentially" the module could allow unsecure configurations.
The temporary workaround that we've made is to make a local clone of your repo and add checkov skip commands in the affected resources. 

Example:
```
#Store the created ssh key in the secrets key vault
resource "azurerm_key_vault_secret" "admin_ssh_key" {
  #checkov:skip=CKV_AZURE_41: "Ensure that the expiration date is set on all secrets"
  #checkov:skip=CKV_AZURE_114: "Ensure that key vault secrets have "content_type" set"
  count = ((var.generate_admin_password_or_ssh_key == true) && (lower(var.virtualmachine_os_type) == "linux")) ? 1 : 0

  key_vault_id = var.admin_credential_key_vault_resource_id
  name         = coalesce(var.admin_generated_ssh_key_vault_secret_name, "${var.name}-${var.admin_username}-ssh-private-key")
  value        = tls_private_key.this[0].private_key_pem
  tags         = var.tags
}
```

However, this is not ideal because we have to manage updates from your repo.
Any thoughts ?
One solution could be that you add these checkov skip commands in your repo and from a big picture point of view,
the whole repo should validated with Checkov:

This way, who consumes the module would be aware of the possibile security risk that could be introduced if the module is not called in a secure way.
What do you think ?

Thanks,
Giovanni

**Comment by jchancellor-ms** [comment]
Thinking this through, the issue here is primarily because we create and store secrets for the user as a way to simplify the installation. I think providing better control of those secrets is a good security practice as you've highlighted.  I will add defaults for the secrets for these and possibly other values and include an additional input interface to customize those configurations from the default.  I hope that will allow for the best initial security posture while also allowing the flexibility for those who wish to customize their installation.  I'll look to add this in 0.14.  Thanks again for calling this to our attention.

**Comment by giovannifl** [comment]
Thanks @jchancellor-ms

**Comment by jchancellor-ms** [comment]
Closing this issue.  Please re-open if problem still exists.
