### ISSUE TITLE
[AVM Module Issue]: Cannot set a Flex Orchestration group to the VM

### ISSUE THREAD

**Issue by mbilalamjad** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#73]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Enterprise Customers HATE random VM naming which is what occurs if you use Flex orchestration to create your VMS. 
The correct way for an Enterprise Customer to deploy is create a VMSS - Flex Resource first. Then when you create a VM you assign it to the Flex resource during deployment. AVM VM Module doesn't surface this functionality.

**Comment by jchancellor-ms** [comment]
@mbilalamjad - I believe the functionality you're asking about is covered by the input `virtual_machine_scale_set_resource_id`.  I've created an example called vmss_flex_vm_attach for this input and will publish it as v0.13.1.

**Comment by mbilalamjad** [comment]
Thank @jchancellor-ms the example in the PR should address this issue, have checked with the feedback submitter also, will go ahead and close this issue.
