### ISSUE TITLE
[AVM Module Issue]: unable to use ubuntu plaintext example

### ISSUE THREAD

**Issue by bradp-nz** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#88]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

Hi, just reaching out as I believe these examples won't work due to the new updates to keyvault. Are we able to rewire this module up? Thanks

**Comment by jchancellor-ms** [comment]
@bradp-nz - Yes, I'm updating all of the example versions and correcting the breaking changes in the Key Vault outputs.  Should have the fixes in the next few days.  I'll be pinning examples on the patch version going forward to avoid this in the future.

**Comment by bradp-nz** [comment]
Thanks @jchancellor-ms appreciate that, looking forward to giving this a spin up!

**Comment by jchancellor-ms** [comment]
@bradp-nz - This has been corrected in 0.15.0.  Please let me know if you encounter issues and we'll re-open and make any necessary corrections.
